/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package local.kcm.dukemarket.gui;
import local.kcm.dukemarket.bean.Produto;
import local.kcm.dukemarket.dao.ProdutoDAO;
/**
 *
 * @author devsys-b
 */
public class Manutencao extends javax.swing.JFrame {

    /**
     * Creates new form Manutencao
     */
    public Manutencao() {
        initComponents();
        
//        // Aparece o codigo e a descrição do produto
//        txtCodigo.setText(String.valueOf(this.produto.getId()));
//        txtDescricao.setText(this.produto.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDes = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblqtd = new javax.swing.JLabel();
        lblCompra = new javax.swing.JLabel();
        lblVenda = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtValorcompra = new javax.swing.JTextField();
        txtValorvenda = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DukeMarket");

        lblDes.setFont(new java.awt.Font("Verdana", 2, 16)); // NOI18N
        lblDes.setText("descrição:");

        lblCod.setFont(new java.awt.Font("Verdana", 2, 16)); // NOI18N
        lblCod.setText("codBarras:");

        lblqtd.setFont(new java.awt.Font("Verdana", 2, 16)); // NOI18N
        lblqtd.setText("qtd:");

        lblCompra.setFont(new java.awt.Font("Verdana", 2, 16)); // NOI18N
        lblCompra.setText("valorcompra:");

        lblVenda.setFont(new java.awt.Font("Verdana", 2, 16)); // NOI18N
        lblVenda.setText("valorvenda:");

        txtCodigo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(51, 51, 255));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtDescricao.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(51, 51, 255));
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        txtValorcompra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtValorcompra.setForeground(new java.awt.Color(51, 51, 255));
        txtValorcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorcompraActionPerformed(evt);
            }
        });

        txtValorvenda.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtValorvenda.setForeground(new java.awt.Color(51, 51, 255));
        txtValorvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorvendaActionPerformed(evt);
            }
        });

        txtQtd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtQtd.setForeground(new java.awt.Color(51, 51, 255));
        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblqtd)
                                .addGap(18, 18, 18)
                                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCod)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDes)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescricao)))
                        .addGap(85, 147, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVenda)
                                .addGap(18, 18, 18)
                                .addComponent(txtValorvenda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCompra)
                                .addGap(18, 18, 18)
                                .addComponent(txtValorcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDes)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblqtd)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompra)
                    .addComponent(txtValorcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnAlterar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtValorcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorcompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorcompraActionPerformed

    private void txtValorvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorvendaActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
      
        Produto pNovo = new Produto();
        ProdutoDAO pDAO = new ProdutoDAO();
        
        //Primeiramente recuperar os dados preenchidos
        pNovo.setCodBarras(txtCodigo.getText());
        pNovo.setDescricao(txtDescricao.getText());
        pNovo.setQtd(Double.parseDouble(txtQtd.getText()));
        pNovo.setValorCompra(Double.parseDouble(txtValorcompra.getText()));
        pNovo.setValorVenda(Double.parseDouble(txtValorvenda.getText()));
        
        pDAO.create(pNovo);
        
        //limparCampos
        txtCodigo.setText("");
        txtQtd.setText("");
        txtDescricao.setText("");
        txtValorcompra.setText("");
        txtValorvenda.setText("");
        
        txtCodigo.requestFocus();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        Produto pAux = new Produto();
        ProdutoDAO pDAO = new ProdutoDAO();
        
        pAux.setCodBarras(txtCodigo.getText());
        pAux.setDescricao(txtDescricao.getText());
        pAux.setQtd(Double.parseDouble(txtQtd.getText()));
        pAux.setValorCompra(Double.parseDouble(txtValorcompra.getText()));
        pAux.setValorVenda(Double.parseDouble(txtValorvenda.getText()));
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manutencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblCompra;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JLabel lblqtd;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtValorcompra;
    private javax.swing.JTextField txtValorvenda;
    // End of variables declaration//GEN-END:variables
}
